### PR TITLE
Add JSON type

### LINKED ISSUE #15: The last column of every record is JSON
@noporpoise proposes in https://github.com/pmelsted/GFA-spec/issues/7#issuecomment-128014521 that the last column of every record is JSON. JSON would replace the current `TAG:TYPE:VALUE` system.

### PR DESCRIPTION
**Pull request by sjackman**
Closes #15

### CODE REVIEW

**Comment by noporpoise** [comment]
:+1:

**Comment by sjackman** [comment]
Vote :+1:

**Comment by lh3** [comment]
Good to me.

**Comment by pmelsted** [comment]
:+1:

**Pull request closed without merging**
